{% set name = "flit-scm" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flit_scm-{{ version }}.tar.gz
  sha256: b9aba5f8eba3fbf34ff523ed23bfe841e29dfa1c6cb87c29cd7f90c378e6f823

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core 3.5.0
    - pip
    - setuptools_scm 6.4.2
    - tomli >=2,<3
  run:
    - python >=3.6
    - flit-core 3.5.0
    - setuptools_scm 6.4.2
    - tomli >=2,<3
test:
  imports:
    - flit_scm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/WillDaSilva/flit_scm
  summary: |
    A PEP 518 build backend that uses setuptools_scm to generate a version file
    from your version control system, then flit_core to build the package.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://gitlab.com/WillDaSilva/flit_scm
  doc_url: https://gitlab.com/WillDaSilva/flit_scm

extra:
  recipe-maintainers:
    - xylar
    - WillDaSilva
